### ISSUE TITLE
Personalized view date pickers in IE 11

### ISSUE THREAD

**Issue by PierreGiboni** [chuck-durst/pit-scheduler#6]
Hi

I have a problem displaying (and changing the CSS) for a right display on IE11 (very large datepickers)

What can I do, the CSS isn't easy to adapt on it ....

I have no problem with chrome but the standard is IE

Thanks

Pierre

**Comment by chuck-durst** [comment]
Hi,

Sorry but that scheduler has not been designed to work well with IE, nor to be edited. It has been tested with Edge but still requires Chrome or at least Firefox for a better experience. 

 I'm not sure to understand what you mean by "right display". Are you trying to make it work in RTL? If the problem is about the datepicker so you may wan't to ask your questions directly to the people managing this project. 

Btw today you can't expect to have a good experience with a browser like IE.
